// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppError = { "Database": string } | { "Io": string } | { "Serialization": string } | { "Tauri": string } | { "Csv": string } | { "Updater": string } | { "Unknown": string };
