// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Deal = { stock_id: string, t: string, c: number, o: number, h: number, l: number, v: bigint, };
