// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryPoint } from "./HistoryPoint";

export type MarketHistory = { id: string, name: string | null, data: Array<HistoryPoint>, price: number, change: number | null, };
