// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MarketTick = { id: string, price: number, change_percent: number, refreshed_ts: bigint, closes: Array<number>, avg_prices: Array<number>, previous_close: number, };
