// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MarketIndicators } from "./MarketIndicators";
import type { MarketTick } from "./MarketTick";

export type MarketEvent = { "type": "Tick", "payload": MarketTick } | { "type": "Indicators", "payload": MarketIndicators };
