// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Skills = { stock_id: string, t: string, ma5: number, ma5_ded: number, ma10: number, ma10_ded: number, ma20: number, ma20_ded: number, ma60: number, ma60_ded: number, ma120: number, ma120_ded: number, macd: number, dif: number, osc: number, k: number, d: number, rsi5: number, rsi10: number, boll_ub: number, boll_ma: number, boll_lb: number, obv: number, obv5: number, j: number | null, };
