import InsightsIcon from "@mui/icons-material/Insights";
import SettingsIcon from "@mui/icons-material/Settings";
import VisibilityIcon from "@mui/icons-material/Visibility";
import { Box, ButtonBase, Typography } from "@mui/material";
import { useTranslation } from "react-i18next";
import { useLocation, useNavigate } from "react-router";
import useUIStore from "../../../store/UI.store";
import { primitiveTokens, semanticTokens } from "../../../theme";
import { BOTTOM_BAR_BOTTOM, BOTTOM_BAR_HEIGHT } from "./constants";
const destinations = [{ path: "/dashboard", label: "navigation.tracking", icon: VisibilityIcon }, { path: "/dashboard/market", label: "navigation.market", icon: InsightsIcon }, { path: "/dashboard/setting", label: "navigation.settings", icon: SettingsIcon }];
export default function BottomBar() { const { t } = useTranslation(); const navigate = useNavigate(); const location = useLocation(); const visible = useUIStore((state) => state.isBottomBarVisible); return <Box role="navigation" aria-label={t("navigation.label")} aria-hidden={!visible} sx={{ position: "fixed", left: "50%", bottom: BOTTOM_BAR_BOTTOM, transform: visible ? "translateX(-50%)" : "translateX(-50%) translateY(120px)", width: "92%", maxWidth: 460, height: BOTTOM_BAR_HEIGHT, display: "grid", gridTemplateColumns: "repeat(3, 1fr)", bgcolor: semanticTokens.app.primary, borderRadius: primitiveTokens.radius.lg, boxShadow: primitiveTokens.shadow.dock, zIndex: primitiveTokens.layer.navigation, opacity: visible ? 1 : 0, visibility: visible ? "visible" : "hidden", pointerEvents: visible ? "auto" : "none", transition: "transform 200ms ease, opacity 200ms ease", "@media (prefers-reduced-motion: reduce)": { transition: "none" } }}>{destinations.map(({ path, label, icon: Icon }) => { const clean = location.pathname.replace(/\/$/, ""); const active = path === "/dashboard" ? clean === "/dashboard" : clean.startsWith(path); return <ButtonBase key={path} tabIndex={visible ? 0 : -1} onClick={() => navigate(path)} aria-current={active ? "page" : undefined} aria-label={t(label)} sx={{ minHeight: 44, color: active ? semanticTokens.app.onPrimary : semanticTokens.app.onPrimaryMuted, display: "flex", flexDirection: "column", gap: .15 }}><Icon fontSize="small" /><Typography variant="caption" fontWeight={active ? 800 : 600}>{t(label)}</Typography></ButtonBase>; })}</Box>; }
